### ISSUE TITLE
Tracking integration for image feature extraction

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface.js#305]
## Tracking integration of task - Feature Extraction

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [ ] Integration with Inference API. Select at least one of the following:
  - [ ] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [ ] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget huggingface/huggingface.js#301 

Integration guide: https://hf.co/docs/hub/adding-a-task

**Comment by osanseviero** [comment]
Closing as per #301
