### ISSUE TITLE
Tracking integration for Video Classification

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface.js#332]
## Tracking integration of task - Video Classification

Example discussion - https://huggingface.co/keras-io/video-transformers/discussions/1#62e9694f1ee086f609b4a500

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [x] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [x] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget

Integration guide: https://hf.co/docs/hub/models-tasks
