### ISSUE TITLE
Tracking integration for `unconditional-image-generation`

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface.js#339]
## Tracking integration of `unconditional-image-generation`

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [x] Integration with Inference API. Select at least one of the following:
  - [x] Added a `diffusers` `pipeline`
  - [x] Added to Community Inference API for 3rd party library
  - [x] Added to Community Inference API for generic
- [ ] Added basic UI elements (icon, order specification, etc)
- [x] Added a task page
- [ ] Added a widget

Integration guide: https://hf.co/docs/hub/models-tasks

**Comment by merveenoyan** [comment]
@osanseviero maybe a seed with slider or number would be appropriate as well. It would be confusing to put no input IMHO.
