### ISSUE TITLE
[Tasks] Spec: follow-up to #449

### ISSUE THREAD

**Issue by SBrandeis** [huggingface/huggingface.js#463]
# TODO

This issue lists the remaining tasks following #449 

- [ ] Ensure the output types of `sentence-similarity` are emitted by the inference-codegen script
- [ ] Packaging/tooling improvements @coyotte508 
- [ ] Add missing parameters for `generate` ([link](https://github.com/huggingface/huggingface.js/blob/4742c9ed37c44bf413f43474e8804e4ea44417f1/packages/tasks/src/tasks/common-definitions.json#L37))
- [ ] Add TEI parameters to the `feature-extraction` / `text-embedding` task
- [ ] Proper prams and descriptions for `depth-estimation` https://github.com/huggingface/transformers/issues/28729

"Bigger" changes:
- [ ] Rename `feature-extraction` to `text-embedding`
- [ ] Unify `text-generation` and `text2text-generation`

**Comment by Wauplin** [comment]
- [ ] in "common parameters" I would rename `GenerationParameters` to `TextGenerationParameters` or `TextGenerationCommonParameters` (to differentiate from other image generation (and audio, video, etc?))

"Bigger changes":
- [ ] add constraints to the values (especially `text_generation` and `text_to_image` float/integer parameters). Constraints might not be reflected in all generated code but will still be useful to document

**Comment by philschmid** [comment]
I was looking into the first added schema and was a bit surprised that they do not match the API schema from inference Endpoints or the Inference API. I thought we wanted to create an external schema that can be used for code generation and other validation to make sure all libraries, API, etc have the same types. 

When i looked into it i saw that the main input is called ["data"](https://github.com/huggingface/huggingface.js/blob/f02c216d3a7f4e86ad3f6c5d48b6101c19a6dcea/packages/tasks/src/tasks/text-generation/spec/input.json#L8) and not "inputs". I also noticed that the "parameters" are "camelCase" and not "snake_case" (in the definitions), Some definitions, e.g. ["text-generation" are only for TGI](https://github.com/huggingface/huggingface.js/blob/f02c216d3a7f4e86ad3f6c5d48b6101c19a6dcea/packages/tasks/src/tasks/text-generation/spec/input.json#L66) and not for the `text-generation` pipeline. 

What's the plan here? I don't think we should maintain definitions that need to be adjusted again to work with our products.
